In [1]:
import pandas as pd

# Price

In [2]:
p = pd.read_csv('/Users/morenomusadat/Proyek Predictive Analytics/Price/Indonesia.csv', sep = ';')
p = p.iloc[::-1]
p.reset_index(drop=True)
p.head()

      Tanggal  Terakhir Pembukaan Tertinggi  Terendah Perubahan%  No
119  01/01/15  12.665,0  12.425,0  12.757,5  12.410,0      2,30%   1
118  01/02/15  12.920,0  12.710,0  12.945,0  12.587,5      2,01%   2
117  01/03/15  13.070,0  12.975,0  13.248,0  12.900,0      1,16%   3
116  01/04/15  12.960,0  13.070,0  13.077,5  12.805,0     -0,84%   4
115  01/05/15  13.223,0  12.985,0  13.243,0  12.976,0      2,03%   5

In [3]:
p2 = p[['Tanggal','Terakhir', 'Tertinggi', 'Terendah', 'No']]
p2

      Tanggal  Terakhir Tertinggi  Terendah   No
119  01/01/15  12.665,0  12.757,5  12.410,0    1
118  01/02/15  12.920,0  12.945,0  12.587,5    2
117  01/03/15  13.070,0  13.248,0  12.900,0    3
116  01/04/15  12.960,0  13.077,5  12.805,0    4
115  01/05/15  13.223,0  13.243,0  12.976,0    5
..        ...       ...       ...       ...  ...
4    01/08/24  15.450,0  16.281,5  15.295,0  116
3    01/09/24  15.135,0  15.583,5  15.065,0  117
2    01/10/24  15.690,0  15.778,5  15.167,5  118
1    01/11/24  15.840,0  15.971,5  15.617,5  119
0    01/12/24  16.090,0  16.322,5  15.830,0  120

[120 rows x 5 columns]

# Import

In [4]:
i15 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2015/20250122150306.xlsx')
i15.iloc[::-1]
i16 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2016/20250122150349.xlsx')
i16.iloc[::-1]
i17 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2017/20250122151924.xlsx')
i18 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2018/20250122152022.xlsx')
i19 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2019/20250122152259.xlsx')
i20 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2020/20250122152356.xlsx')
i21 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2021/20250122152623.xlsx')
i22 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2022/20250122152717.xlsx')
i23 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2023/20250122152741.xlsx')
i24 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Import/2024/20250122145502.xlsx')

In [5]:
i15['index'] = 2015
i16['index'] = 2016
i17['index'] = 2017
i18['index'] = 2018
i19['index'] = 2019
i20['index'] = 2020
i21['index'] = 2021
i22['index'] = 2022
i23['index'] = 2023
i24['index'] = 2024

In [6]:
cidf = pd.concat([i15,i16,i17,i18,i19,i20,i21,i22,i23,i24], ignore_index=True)
cidf

,Tahun,Total,Consumption Goods,Raw Material Support,Capital Goods,index
0,Desember,"12,077.30","1,083.50","8,749.37","2,244.44",2015
1,November,"11,519.47",954.44,"8,539.78","2,025.25",2015
2,Oktober,"11,108.92",770.32,"8,275.39","2,063.21",2015
3,September,"11,558.60",856.55,"8,663.96","2,038.09",2015
4,Agustus,"12,399.25","1,108.50","9,250.59","2,040.15",2015
...,...,...,...,...,...,...
115,Mei,"21,279.59","2,068.54","15,306.64","3,904.42",2024
116,April,"15,347.61","1,398.17","11,597.87","2,351.57",2024
117,Maret,"20,588.05","1,761.45","15,114.16","3,712.44",2024
118,Februari,"15,919.17","1,364.09","11,791.92","2,763.16",2024
119,Januari,"18,442.93","1,596.24","13,886.90","2,959.79",2024

In [7]:
cidf.isna().sum()

Tahun                   0
Total                   0
Consumption Goods       0
Raw Material Support    0
Capital Goods           0
index                   0
dtype: int64

In [8]:
cidf2 = cidf[['Total']]
cidf2.columns = ['Total Import']
cidf2

    Total Import
0      12,077.30
1      11,519.47
2      11,108.92
3      11,558.60
4      12,399.25
..           ...
115    21,279.59
116    15,347.61
117    20,588.05
118    15,919.17
119    18,442.93

[120 rows x 1 columns]

# Export

In [16]:
e15 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2015/Ekspor (1).xlsx')
e16 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2016/Ekspor (1).xlsx')
e17 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2017/Ekspor (1).xlsx')
e18 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2018/Ekspor (1).xlsx')
e19 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2019/Ekspor (1).xlsx')
e20 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2020/Ekspor (1).xlsx')
e21 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2021/Ekspor (1).xlsx')
e22 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2022/Ekspor (1).xlsx')
e23 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2023/Ekspor (1).xlsx')
e24 = pd.read_excel('/Users/morenomusadat/Proyek Predictive Analytics/Export/2024/Ekspor (1).xlsx')

In [17]:
e15['index'] = 2015
e16['index'] = 2016
e17['index'] = 2017
e18['index'] = 2018
e19['index'] = 2019
e20['index'] = 2020
e21['index'] = 2021
e22['index'] = 2022
e23['index'] = 2023
e24['index'] = 2024

In [18]:
cedf = pd.concat([e15,e16,e17,e18,e19,e20,e21,e22,e23,e24], ignore_index=True)
cedf

,Tahun,Total,MIGAS,NON MIGAS,Agriculture,Industry,Mining,Others,index
0,Desember,"11,917.11","1,299.48","10,617.63",288.69,"8,639.01","1,660.47",29.46,2015
1,November,"11,122.18","1,497.03","9,625.15",293.38,"8,045.91","1,257.17",28.68,2015
2,Oktober,"12,121.74","1,379.55","10,742.19",342.00,"9,095.56","1,269.32",35.30,2015
3,September,"12,588.36","1,453.56","11,134.80",374.21,"9,152.72","1,572.35",35.53,2015
4,Agustus,"12,726.04","1,530.88","11,195.16",415.56,"9,057.17","1,688.07",34.36,2015
...,...,...,...,...,...,...,...,...,...
114,Mei,"22,325.54","1,419.11","20,906.44",400.19,"16,292.77","4,174.00",39.48,2024
115,April,"19,614.86","1,349.97","18,264.89",300.39,"13,999.40","3,940.17",24.92,2024
116,Maret,"22,537.69","1,285.24","21,252.45",432.27,"16,656.70","4,124.23",39.25,2024
117,Februari,"19,272.86","1,216.91","18,055.95",371.06,"13,620.95","4,034.37",29.57,2024
118,Januari,"20,493.10","1,397.57","19,095.53",374.73,"15,024.30","3,670.81",25.69,2024

In [19]:
cedf2 = cedf[['Total']]
cedf2.columns = ['Total Export']
cedf2

    Total Export
0      11,917.11
1      11,122.18
2      12,121.74
3      12,588.36
4      12,726.04
..           ...
114    22,325.54
115    19,614.86
116    22,537.69
117    19,272.86
118    20,493.10

[119 rows x 1 columns]

In [20]:
result = pd.concat([p2,cidf2, cedf2], axis=1, ignore_index=False)
display(result)

      Tanggal  Terakhir Tertinggi  Terendah   No Total Import Total Export
119  01/01/15  12.665,0  12.757,5  12.410,0    1    18,442.93          NaN
118  01/02/15  12.920,0  12.945,0  12.587,5    2    15,919.17    20,493.10
117  01/03/15  13.070,0  13.248,0  12.900,0    3    20,588.05    19,272.86
116  01/04/15  12.960,0  13.077,5  12.805,0    4    15,347.61    22,537.69
115  01/05/15  13.223,0  13.243,0  12.976,0    5    21,279.59    19,614.86
..        ...       ...       ...       ...  ...          ...          ...
4    01/08/24  15.450,0  16.281,5  15.295,0  116    12,399.25    12,726.04
3    01/09/24  15.135,0  15.583,5  15.065,0  117    11,558.60    12,588.36
2    01/10/24  15.690,0  15.778,5  15.167,5  118    11,108.92    12,121.74
1    01/11/24  15.840,0  15.971,5  15.617,5  119    11,519.47    11,122.18
0    01/12/24  16.090,0  16.322,5  15.830,0  120    12,077.30    11,917.11

[120 rows x 7 columns]

# Cadangan Devisa

In [23]:
cdngan_dev = '/Users/morenomusadat/Proyek Predictive Analytics/Cadangan Devisa/cadangan devisa_databoks.xlsx'
cadangan_devisa_df = pd.read_excel(cdngan_dev)
cadangan_devisa_df.head()

         date    value
0  2001-01-31  29257.0
1  2001-02-28  29107.0
2  2001-03-31  28673.0
3  2001-04-30  28713.0
4  2001-05-31  28594.0